DROP TABLE IF EXISTS users

CREATE TABLE IF NOT EXISTS users(
		uid serial PRIMARY KEY,
		username VARCHAR (50) UNIQUE NOT NULL,
		password VARCHAR (100) NOT NULL,
		email VARCHAR (355) UNIQUE NOT NULL,
		created_on TIMESTAMP NOT NULL,
		last_login TIMESTAMP
	 );